<?php

return [
    'permissions' => [
        'products' => 'کالاها',
        'discounts' => 'تخفیف‌ها',
        'posts' => 'پست‌ها و دسته‌بندی',
        'packing' => 'بسته‌بندی',
        'settings' => 'تنظیمات سایت',
        'reports' => 'گزارش‌ها',
        'queue' => 'مانیتورینگ جاب‌ها',
        'users' => 'دسترسی کارکنان',
    ],

    /*
     * null = هر کاربر type=user (کارکنان) مجاز است.
     * آرایه = داشتن حداقل یکی از مجوزها کافی است.
     * اگر روت ادمین در این لیست نباشد، فقط مدیرکل مجاز است.
     */
    'route_permissions' => [
        'A_home' => null,
        'dashboard' => null,

        'A_show_product' => 'products',
        'A_create_product' => 'products',
        'ajax_A_create_product' => 'products',
        'A_s_create_product' => 'products',
        'A_edit_product' => 'products',
        'A_s_edit_product' => 'products',
        'A_inactive_product' => 'products',
        'A_select_new_products' => 'products',
        'A_s_select_new_products' => 'products',

        'A_show_discount' => 'discounts',
        'A_create_discount' => 'discounts',
        'A_s_create_discount' => 'discounts',
        'A_edit_discount' => 'discounts',
        'A_s_edit_discount' => 'discounts',
        'A_inactive_discount' => 'discounts',
        'A_show_amazingsale' => 'discounts',
        'A_show_common_discount' => 'discounts',
        'A_create_amazingsale' => 'discounts',
        'A_create_common_discount' => 'discounts',
        'A_s_create_amazingsale' => 'discounts',
        'A_s_create_common_discount' => 'discounts',
        'A_edit_amazingsale' => 'discounts',
        'A_s_edit_amazingsale' => 'discounts',
        'A_edit_common_discount' => 'discounts',
        'A_s_edit_common_discount' => 'discounts',
        'A_inactive_amazingsale' => 'discounts',
        'A_inactive_common_discount' => 'discounts',

        'A_create_post' => 'posts',
        'A_edit_post' => 'posts',
        'A_s_create_post' => 'posts',
        'A_s_edit_post' => 'posts',
        'A_s_status_post' => 'posts',
        'A_posts' => 'posts',
        'A_ajax_get_posts' => 'posts',
        'A_ajax_image_uploader' => 'posts',
        'ajax_check_slug_title' => 'posts',
        'A_ajax_remove_image' => 'posts',
        'A_ajax_remove_file' => 'posts',
        'A_create_category' => 'posts',
        'A_edit_category' => 'posts',
        'A_s_create_category' => 'posts',
        'A_s_edit_category' => 'posts',
        'A_categories' => 'posts',
        'A_parents_categories' => 'posts',
        'A_show_category_tree' => 'posts',

        'A_setting' => 'settings',
        'A_edit_about' => 'settings',
        'A_edit_contact' => 'settings',
        'A_contact_messages' => ['settings', 'reports'],
        'A_generate_sitemap' => 'settings',
        'A_edit_frequently_asked_questions' => 'settings',
        'A_s_edit_frequently_asked_questions' => 'settings',
        'A_delete_frequently_asked_questions' => 'settings',
        'A_update_frequently_asked_questions' => 'settings',
        'A_s_edit_company_info' => 'settings',
        'A_s_edit_about' => 'settings',

        'A_queue_monitor' => 'queue',
        'A_queue_monitor_start' => 'queue',
        'A_queue_monitor_stop' => 'queue',
        'A_queue_monitor_retry' => 'queue',
        'A_queue_monitor_retry_all' => 'queue',

        'A_report_of_exhibition_customers' => 'reports',
        'A_report_of_site_customers' => 'reports',
        'A_report_of_per_customer' => 'reports',
        'A_report_of_orders' => 'reports',
        'A_report_of_order_items' => 'reports',
        'A_report_of_exhibition_visitors' => 'reports',
        'A_report_of_exhibition_visitors_by_city' => 'reports',

        'A_product_packing_list' => 'packing',
        'A_post_packing_list' => 'packing',
        'A_carton_list' => 'packing',
        'ajax_carton_list' => 'packing',
        'ajax_fetch_packing' => 'packing',
        'ajax_save_packing' => 'packing',
        'ajax_product_packing_list' => 'packing',
        'A_delete_packing' => 'packing',
        'ajax_post_packing_list' => 'packing',
        'ajax_post_packing_update' => 'packing',
        'ajax_post_packing_create_pattern' => 'packing',

        'A_staff_access' => 'users',
        'A_s_staff_access' => 'users',
    ],
];
